/* 
 * File:   Interrupt_gen_cfg.h
 * Author: smart
 *
 * Created on 27 , 7 , 2024, 01:02 ?
 */

#ifndef INTERRUPT_GEN_CFG_H
#define	INTERRUPT_GEN_CFG_H

#define FEATURE_ENABLE                              1
//#define INTERRUPT_PRIORITY_LEVELS_ENABLE            FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE      FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_OnChange_FEATURE_ENABLE  FEATURE_ENABLE
#define ADC_INTERRUPT_FEATURE_ENABLE                FEATURE_ENABLE
#define TIMER0_INTERRUPT_FEATURE_ENABLE             FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE_ENABLE             FEATURE_ENABLE
#define TIMER2_INTERRUPT_FEATURE_ENABLE             FEATURE_ENABLE
#define TIMER3_INTERRUPT_FEATURE_ENABLE             FEATURE_ENABLE
#define CCP1_INTERRUPT_FEATURE_ENABLE               FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE_ENABLE               FEATURE_ENABLE
#define EUSART_TX_INTERRUPT_FEATURE_ENABLE          FEATURE_ENABLE
#define EUSART_RX_INTERRUPT_FEATURE_ENABLE          FEATURE_ENABLE
//#define MSSP_I2C_INTERRUPT_FEATURE_ENABLE           FEATURE_ENABLE
//#define MSSP_SPI_INTERRUPT_FEATURE_ENABLE           FEATURE_ENABLE

#endif	/* INTERRUPT_GEN_CFG_H */

